# Generated by Django 5.0.2 on 2024-03-17 02:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_user_email_verified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="business_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="industry",
        ),
    ]
