# Generated by Django 5.0.2 on 2024-03-21 03:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_remove_user_business_name_remove_user_industry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="user_avatars"),
        ),
    ]
