# Generated by Django 5.0.2 on 2024-03-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0005_alter_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="has_answered_questionnaire",
            field=models.BooleanField(default=False),
        ),
    ]
