# Generated by Django 5.0.2 on 2024-03-25 18:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0006_user_has_answered_questionnaire"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="has_answered_questionnaire",
            new_name="has_completed_questionnaire",
        ),
    ]
