# Generated by Django 5.0.2 on 2024-05-07 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "account",
            "0007_rename_has_answered_questionnaire_user_has_completed_questionnaire",
        ),
        ("business", "0008_alter_business_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="default_company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="defaulted_by",
                to="business.business",
            ),
        ),
    ]
