# Generated by Django 5.0.2 on 2024-05-17 03:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BillingPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("4d033826-b8c8-4802-b378-c8f29bebf636"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("price", models.IntegerField()),
                ("duration", models.IntegerField(help_text="duration in days")),
                (
                    "frequency",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("yearly", "Yearly")],
                        default="monthly",
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("b53ff490-9cef-4797-b266-cd3a77d03924"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount_paid", models.DecimalField(decimal_places=3, max_digits=10)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("invoice_number", models.CharField(max_length=100, unique=True)),
                (
                    "billing_plan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="payment.billingplan",
                    ),
                ),
            ],
        ),
    ]
