# Generated by Django 5.0.2 on 2024-02-27 18:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingplan",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("1436a9b5-9ef6-4e48-8e6b-8f54f69d4d3d"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("7fde71cb-5b06-49b8-bc94-f1e279332a05"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
