# Generated by Django 5.0.2 on 2024-02-28 20:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0002_alter_billingplan_id_alter_invoice_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingplan",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("3ba31b5f-98f5-42b0-a1ae-a09dd1e78638"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("b3867fb8-604c-4d18-9ba1-17de2c63d7c2"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
