# Generated by Django 5.0.2 on 2024-05-17 04:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingplan",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("5091aeed-aa7e-4dde-ba8b-affebe8e319f"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("dc27c29e-1f3b-4c2d-be52-a65d1bdbd7fe"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
