# Generated by Django 5.0.2 on 2024-03-03 01:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0003_alter_billingplan_id_alter_invoice_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingplan",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("ffdb6bb9-4c9d-400e-98f4-914255ed9f93"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("87854718-1970-4d35-8c32-b599ff66b658"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
