# Generated by Django 5.0.2 on 2024-03-03 04:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0004_alter_billingplan_id_alter_invoice_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingplan",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("bef9fab6-9b39-45b3-9422-397b34b4c294"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("de33b94c-5a20-4069-8988-58668cc429b5"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
