# Generated by Django 5.0.2 on 2024-05-18 10:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0004_alter_billingplan_id_alter_invoice_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingplan",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("ca7c28c7-5202-4917-a134-4cddc228afd5"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("1af7a89d-2d37-4b8f-b7df-7b1fa62a8ea7"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
