# Generated by Django 5.0.2 on 2024-03-06 07:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0005_alter_billingplan_id_alter_invoice_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingplan",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("9c3c9c96-f75a-4eff-8a46-924a42cd01df"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("5579afa6-9af5-4124-8792-41b0a146047f"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
