# Generated by Django 5.0.2 on 2024-05-18 10:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0005_alter_billingplan_id_alter_invoice_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingplan",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("f0692c9a-6915-477f-93e3-13e376847529"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("b4f959e8-e157-4e3b-aa23-d6417fb8b281"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
