# Generated by Django 5.0.2 on 2024-03-06 07:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0006_alter_billingplan_id_alter_invoice_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingplan",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("200a26e6-d96e-433e-8964-de8fae56b6e5"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("67e7637c-5df8-4167-adaf-3b155d9d52f3"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
