# Generated by Django 5.0.2 on 2024-05-19 04:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0006_alter_billingplan_id_alter_invoice_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingplan",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("01f1f4c9-610d-4588-836c-302e18394461"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("d45cbe17-d21c-4f8e-a0e1-ef6e9743c2b9"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
