# Generated by Django 5.0.2 on 2024-03-06 07:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0007_alter_billingplan_id_alter_invoice_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingplan",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("3ffe8881-2f2f-4f63-ad96-ca3349fcee2d"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("f62aa5ed-ff31-49f8-aa4b-456f93f51e4e"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
