# Generated by Django 5.0.2 on 2024-05-22 03:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0007_alter_billingplan_id_alter_invoice_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingplan",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("10018cdf-cde0-478b-ad89-311957b05302"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("81cbc1da-1988-4cfd-921f-95fa55945d27"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
