# Generated by Django 5.0.2 on 2024-03-06 08:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0008_alter_billingplan_id_alter_invoice_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingplan",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("6fdb0a84-9f1b-4548-8c8c-de520e1621ce"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("8a23db6c-8df8-45be-ae66-09fc6c308f0b"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
