# Generated by Django 5.0.2 on 2024-05-22 03:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0008_alter_billingplan_id_alter_invoice_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingplan",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("ac05d0f7-4bae-4b02-8a6f-871cfdfeceb3"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("0826fd62-b3f0-46d2-a404-9c10c6cf548c"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
