# Generated by Django 5.0.2 on 2024-05-22 04:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0009_alter_billingplan_id_alter_invoice_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingplan",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("b55b51ce-a79e-49f7-9867-3753e171c397"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("54553692-277c-4684-bfae-5f7f879e5f28"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
