# Generated by Django 5.0.2 on 2024-03-06 20:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0009_alter_billingplan_id_alter_invoice_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingplan",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("a67324df-cbce-4b56-a8cc-f72ef18f672f"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("574652b1-35cc-46c8-95cd-dcdb8f21c0db"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
