# Generated by Django 5.0.2 on 2024-03-06 20:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0010_alter_billingplan_id_alter_invoice_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingplan",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("6cb533c1-571b-4fd2-baf1-a17326981774"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("d125b144-cdcf-4653-a0c3-33a40038811a"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
