# Generated by Django 5.0.2 on 2024-05-22 06:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0010_alter_billingplan_id_alter_invoice_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingplan",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("7b642ac5-9b23-4ac7-a1f5-eb4450bb25ce"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("e82b1ce2-4859-4d88-805c-4902610e2928"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
