# Generated by Django 5.0.2 on 2024-05-22 17:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0011_alter_billingplan_id_alter_invoice_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingplan",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("24f27cff-6a9a-4899-ac9b-f32f6c983c63"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("405f1c01-008f-46b6-8080-24bdd49cdbac"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
