# Generated by Django 5.0.2 on 2024-03-07 17:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0011_alter_billingplan_id_alter_invoice_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingplan",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("2f224425-1b5d-4782-8d94-401869a80b95"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("bb584646-10dd-4fb5-b412-75828d96848d"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
