# Generated by Django 5.0.2 on 2024-03-07 17:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0012_alter_billingplan_id_alter_invoice_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingplan",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("e3fc73d4-50a4-4811-9288-3f6eacfeea44"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("9c6e2d20-97c4-4d32-ba4a-98b99a76b1e1"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
