# Generated by Django 5.0.2 on 2024-05-22 21:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0012_alter_billingplan_id_alter_invoice_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingplan",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("4f05abb5-ec0e-49bc-8b25-6bc8f6b50c3d"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("49ca65a9-57c4-40be-85ea-9cab102cee5e"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
