# Generated by Django 5.0.2 on 2024-03-07 17:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0013_alter_billingplan_id_alter_invoice_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingplan",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("3fa6e449-bc53-4141-b1b6-068924ce6b0d"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("3b2572b5-3785-43db-906b-2d9c68c9f5e1"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
