# Generated by Django 5.0.2 on 2024-03-07 17:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0014_alter_billingplan_id_alter_invoice_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingplan",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("4dd5ebc7-6cae-4270-97a5-ebc07117a85c"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("a3577fca-7bb9-4526-86ef-fc7e5c92c7fa"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
