# Generated by Django 5.0.2 on 2024-05-23 21:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0014_alter_billingplan_id_alter_invoice_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingplan",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("b6f00b22-3228-4571-a686-fe3561c45149"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("5d45d869-47f3-47e7-81e2-2c37e6f65f99"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
