# Generated by Django 5.0.2 on 2024-03-07 17:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0015_alter_billingplan_id_alter_invoice_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingplan",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("a91ef708-f0e3-4f0f-9827-d8fa2cd4663a"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("879b0b18-e8b6-4155-b307-a55a008cb09f"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
