# Generated by Django 5.0.2 on 2024-05-23 22:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0015_alter_billingplan_id_alter_invoice_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingplan",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("58b6ca63-2ddd-494c-bfba-b8cfa54721a1"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("84d50585-2d3e-4079-8921-427269238170"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
