# Generated by Django 5.0.2 on 2024-03-07 18:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0016_alter_billingplan_id_alter_invoice_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingplan",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("623ea343-c6d7-4909-acd2-4c23538b97fd"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("a736de72-85b4-4fed-a469-bf86e6844b93"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
