# Generated by Django 5.0.2 on 2024-03-07 18:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0017_alter_billingplan_id_alter_invoice_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingplan",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("dc849bc8-fa30-4bea-88ee-75edc6f006a8"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("47560fa0-131f-4d6c-9f52-f0c5049d765d"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
