# Generated by Django 5.0.2 on 2024-05-24 00:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0017_alter_billingplan_id_alter_invoice_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingplan",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("529e7f04-345b-4dd8-a30d-76875ad1eb33"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("a1519f39-49ec-4a1a-9321-a32d82590f97"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
