# Generated by Django 5.0.2 on 2024-03-17 02:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0018_alter_billingplan_id_alter_invoice_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingplan",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("81d5a430-f5cd-4193-b2eb-bb42b5fc5f34"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("70b071fa-c645-4031-8bf3-29d55f8bdb91"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
