# Generated by Django 5.0.2 on 2024-05-24 00:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0018_alter_billingplan_id_alter_invoice_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingplan",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("de80a375-eb11-4481-af7a-57fe9769f9aa"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("6cf4b03d-ecb6-4145-aedb-c6d3cc1ba510"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
