# Generated by Django 5.0.2 on 2024-03-21 03:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0019_alter_billingplan_id_alter_invoice_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingplan",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("aa2d0b52-08b6-41b1-aff9-980fe7603c77"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("538221bc-057b-4826-8f8b-53b545802c51"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
