# Generated by Django 5.0.2 on 2024-05-24 23:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0019_alter_billingplan_id_alter_invoice_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingplan",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("1c84e504-74f4-4941-b164-0e11bafd7454"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("8508b787-ffbd-4ec7-b1e6-068a0039cb7e"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
