# Generated by Django 5.0.2 on 2024-05-24 23:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0020_alter_billingplan_id_alter_invoice_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingplan",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("44103182-7a4e-44f6-a923-d05abcbd6043"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("d17d0cef-48bd-4fec-960a-f3f7773db2e4"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
