# Generated by Django 5.0.2 on 2024-03-21 03:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0020_alter_billingplan_id_alter_invoice_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingplan",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("9f02fefb-9aa9-4503-96c3-96e8869cb284"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("52f5dab1-7ce6-4551-8a08-a13bc357b9d3"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
