# Generated by Django 5.0.2 on 2024-03-25 18:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0021_alter_billingplan_id_alter_invoice_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingplan",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("f82500de-ac8f-40c2-91bb-1fddafcb5330"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("005f7fa8-e480-4387-9434-84a0293dbcc5"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
