# Generated by Django 5.0.2 on 2024-03-25 18:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0022_alter_billingplan_id_alter_invoice_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingplan",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("55ee760c-2777-4160-b809-e6316b08b366"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("1f72312d-db7c-4384-9b50-0e085e4edf4d"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
