# Generated by Django 5.0.2 on 2024-05-02 05:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0024_alter_billingplan_id_alter_invoice_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingplan",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("cb59f588-c0e9-4f78-8a74-c75d2ded0ffe"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("7873c347-4ef3-4746-9f4f-a6d8362f12e0"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
