# Generated by Django 5.0.2 on 2024-05-02 07:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0025_alter_billingplan_id_alter_invoice_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingplan",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("49bb91e6-4dfb-421d-b641-fd19972e49f1"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("f45a3abc-6413-4315-844e-f55e3c5412d8"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
