# Generated by Django 5.0.2 on 2024-05-02 09:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0026_alter_billingplan_id_alter_invoice_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingplan",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("0627de65-afe7-4ae7-9910-b2b4b083a3bb"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("92704cab-6cf7-48b7-aed4-921ba9406801"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
