# Generated by Django 5.0.2 on 2024-05-02 19:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0028_alter_billingplan_id_alter_invoice_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingplan",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("5cfc0ac7-0946-4342-9620-4ecfc5d4123b"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("b0655c6f-3c0a-4724-b5aa-79ceaa240c80"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
