# Generated by Django 5.0.2 on 2024-05-02 20:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0029_alter_billingplan_id_alter_invoice_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingplan",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("ea5de62a-9040-464a-87e8-868f96efa30d"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("cbdfb3d9-1bdb-489a-bdb1-3793589406d3"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
