# Generated by Django 5.0.2 on 2024-05-03 14:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0030_alter_billingplan_id_alter_invoice_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingplan",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("13a05189-7c0f-4ca0-a348-c36f8f93390e"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("7a35a5a2-aded-4e1b-8568-451abff55857"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
