# Generated by Django 5.0.2 on 2024-05-07 05:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0031_alter_billingplan_id_alter_invoice_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingplan",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("6996acee-3bff-4f57-8f47-24f136a16750"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("331476bc-d687-44ef-9d62-96ecc56348ea"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
