# Generated by Django 5.0.2 on 2024-05-07 06:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0032_alter_billingplan_id_alter_invoice_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingplan",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("1d3096f9-47a1-4761-906d-4e37b0ec65ec"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("91b77e14-23e5-41ee-842b-b4ecd87ea630"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
