# Generated by Django 5.0.2 on 2024-05-22 03:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Questions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("questions", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="userresponse",
            name="answer",
        ),
        migrations.RemoveField(
            model_name="category",
            name="industries",
        ),
        migrations.RemoveField(
            model_name="specificquestion",
            name="category",
        ),
        migrations.RemoveField(
            model_name="userresponse",
            name="question",
        ),
        migrations.AddField(
            model_name="userresponse",
            name="responses",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userresponse",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="response",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="AnswerOption",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="SpecificQuestion",
        ),
    ]
