# Generated by Django 5.0.2 on 2024-02-22 09:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("questionnaire", "0002_alter_category_name_alter_industry_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="specificquestion",
            old_name="business_type",
            new_name="category",
        ),
    ]
