# Generated by Django 5.0.2 on 2024-05-22 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0002_questions_remove_userresponse_answer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userresponse",
            name="time",
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
