# Generated by Django 5.0.2 on 2024-05-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0003_userresponse_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="questions",
            name="time",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
