# Generated by Django 5.0.2 on 2024-02-27 18:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questionnaire", "0003_rename_business_type_specificquestion_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("f358a2ef-7082-4fcc-94b8-f9226b31d8a7"),
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("score", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_score",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
