# Generated by Django 5.0.2 on 2024-05-23 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0004_questions_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="questions",
            name="number_of_questions",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
