# Generated by Django 5.0.2 on 2024-02-27 18:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questionnaire", "0004_businessscore"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessscore",
            name="date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="businessscore",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("58e1b17c-3a97-4d5c-a610-a5b378aa72d5"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
