# Generated by Django 5.0.2 on 2024-05-23 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0005_questions_number_of_questions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questions",
            name="number_of_questions",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
