# Generated by Django 5.0.2 on 2024-02-28 20:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questionnaire", "0005_businessscore_date_alter_businessscore_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessscore",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("c9bd16c3-db4f-43b8-855e-d175e97793af"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
