# Generated by Django 5.0.2 on 2024-05-23 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0006_alter_questions_number_of_questions"),
    ]

    operations = [
        migrations.AddField(
            model_name="userresponse",
            name="ratio_completed",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
