# Generated by Django 5.0.2 on 2024-03-03 04:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questionnaire", "0007_category_industries_alter_businessscore_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessscore",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("80ed0bad-a847-4cb6-87df-11b0fb3642d9"),
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="industries",
            field=models.ManyToManyField(
                blank=True, related_name="categories", to="questionnaire.industry"
            ),
        ),
    ]
