# Generated by Django 5.0.2 on 2024-03-06 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0002_alter_businessscore_id"),
        ("questionnaire", "0008_alter_businessscore_id_alter_category_industries"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userresponse",
            name="user",
        ),
        migrations.AddField(
            model_name="userresponse",
            name="business",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="response",
                to="business.business",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userresponse",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="response",
                to="questionnaire.specificquestion",
            ),
        ),
        migrations.DeleteModel(
            name="BusinessScore",
        ),
    ]
