# Generated by Django 5.0.2 on 2024-05-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="aichatmessage",
            old_name="message",
            new_name="query",
        ),
        migrations.AddField(
            model_name="aichatmessage",
            name="response",
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
