# Generated by Django 5.0.2 on 2024-05-24 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_account", "0003_user_quickbooks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="quickbooks",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
