# Generated by Django 5.0.2 on 2024-05-24 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_account", "0004_alter_user_quickbooks"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="quickbooks",
        ),
    ]
