# Generated by Django 5.0.2 on 2024-03-06 07:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("questionnaire", "0008_alter_businessscore_id_alter_category_industries"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Business",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "industry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business",
                        to="questionnaire.industry",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BusinessScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("a9580b21-51fc-43ff-8495-0a1050dbf8f0"),
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("score", models.IntegerField()),
                ("date", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score",
                        to="business.business",
                    ),
                ),
            ],
        ),
    ]
