# Generated by Django 5.0.2 on 2024-03-06 07:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessscore",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("c823157e-e0cd-41fd-afa0-ce0abb748b92"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
