# Generated by Django 5.0.2 on 2024-05-17 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("business", "0001_initial"),
        ("questionnaire", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="industry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="business",
                to="questionnaire.industry",
            ),
        ),
    ]
