# Generated by Django 5.0.2 on 2024-03-06 07:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0002_alter_businessscore_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessscore",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("9fdf5e4e-a8b0-4bbd-8bf1-5839f16c34aa"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
