# Generated by Django 5.0.2 on 2024-03-06 08:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0003_alter_businessscore_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="business",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="business",
            name="date_founded",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="business",
            name="facebook_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="business",
            name="legal_status",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="business",
            name="linkedin_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="business",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="business_profile"
            ),
        ),
        migrations.AddField(
            model_name="business",
            name="postal_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="business",
            name="state_province",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="business",
            name="street_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="business",
            name="tax_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="business",
            name="twitter_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="business",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("a3b11ff7-d501-4960-8780-29653429396e"),
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="businessscore",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("b9535c1b-ce72-4f18-b1b4-1b9b6fe40858"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
