# Generated by Django 5.0.2 on 2024-03-06 20:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "business",
            "0004_business_city_business_country_business_date_founded_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="businessscore",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("be4811a4-39bf-444e-9dfe-376af360c8a5"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
