# Generated by Django 5.0.2 on 2024-05-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0004_businessscore_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessscore",
            name="score",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
