# Generated by Django 5.0.2 on 2024-03-06 20:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0005_alter_business_id_alter_businessscore_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessscore",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
