# Generated by Django 5.0.2 on 2024-05-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0005_alter_businessscore_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="has_completed_questionnaire",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
