# Generated by Django 5.0.2 on 2024-03-17 02:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0007_alter_business_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="business_profile/"
            ),
        ),
    ]
