# Generated by Django 5.0.2 on 2024-05-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0007_business_has_connected_quickbooks"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessscore",
            name="quickbooks_score_differentiator",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
