# Generated by Django 5.0.2 on 2024-05-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("miners", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quickbookstoken",
            name="access_token",
            field=models.CharField(max_length=1025),
        ),
        migrations.AlterField(
            model_name="quickbookstoken",
            name="refresh_token",
            field=models.CharField(max_length=1025),
        ),
        migrations.AlterField(
            model_name="quickbookstoken",
            name="token_type",
            field=models.CharField(max_length=255),
        ),
    ]
