# Generated by Django 5.0.2 on 2024-05-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("miners", "0002_alter_quickbookstoken_access_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quickbookstoken",
            name="realm_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
