# Generated by Django 5.0.2 on 2024-05-24 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0006_business_has_completed_questionnaire"),
        ("miners", "0004_quickbookstoken_quickbooks_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="quickbookstoken",
            name="business_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quickbooks",
                to="business.business",
            ),
        ),
        migrations.AlterField(
            model_name="quickbookstoken",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quickbooks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
